#!/bin/sh
### BEGIN INIT INFO
# Provides:          <SERVICE>
# Required-Start:    docker
# Required-Stop:     docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

CONTAINER=<CONTAINER>

case "$1" in
  start|stop|restart|pause|unpause|wait|attach|build|commit|diff|export|inspect|kill|logs|rm)
    docker $* $CONTAINER
    ;;
  cp)
    docker cp $CONTAINER:$2 $3
  ;;
  port)
    docker cp $CONTAINER $2
  ;;
  top)
    if [ -z $2 ]
    then
      docker top $CONTAINER
    else
      shift
      docker top $CONTAINER ps $*
    fi
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|pause|unpause|wait|attach|build|commit|diff|export|inspect|kill|logs|rm|cp|port|top}"
esac
