#!/bin/sh
### BEGIN INIT INFO
# Provides:          <SERVICE>
# Required-Start:    docker
# Required-Stop:     docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

CONTAINER=<CONTAINER>

function usage {
  cat <<EOF
<DESCRIPTION>

Usage: $0 {start|stop|restart|pause|unpause|wait|attach|commit|diff|export|inspect|kill|logs|rm|cp|port|top}
EOF
}

function pre_start {
### BEGIN PRE_START_SCRIPT ###
###  END  PRE_START_SCRIPT ###
}

function post_start {
### BEGIN POST_START_SCRIPT ###
###  END  POST_START_SCRIPT ###
}

function pre_stop {
### BEGIN PRE_STOP_SCRIPT ###
###  END  PRE_STOP_SCRIPT ###
}

function post_stop {
### BEGIN POST_STOP_SCRIPT ###
###  END  POST_STOP_SCRIPT ###
}

function pre_restart {
### BEGIN PRE_RESTART_SCRIPT ###
###  END  PRE_RESTART_SCRIPT ###
}

function post_restart {
### BEGIN POST_RESTART_SCRIPT ###
###  END  POST_RESTART_SCRIPT ###
}

function pre_pause {
### BEGIN PRE_PAUSE_SCRIPT ###
###  END  PRE_PAUSE_SCRIPT ###
}

function post_pause {
### BEGIN POST_PAUSE_SCRIPT ###
###  END  POST_PAUSE_SCRIPT ###
}

function pre_unpause {
### BEGIN PRE_UNPAUSE_SCRIPT ###
###  END  PRE_UNPAUSE_SCRIPT ###
}

function post_unpause {
### BEGIN POST_UNPAUSE_SCRIPT ###
###  END  POST_UNPAUSE_SCRIPT ###
}

case "$1" in
  start)
    pre_start
    docker $* $CONTAINER
    post_start
    ;;
  stop)
    pre_stop
    docker $* $CONTAINER
    post_stop
    ;;
  restart)
    pre_restart
    docker $* $CONTAINER
    post_restart
    ;;
  pause)
    pre_pause
    docker $* $CONTAINER
    post_pause
    ;;
  unpause)
    pre_unpause
    docker $* $CONTAINER
    post_unpause
    ;;
  wait|attach|commit|diff|export|inspect|kill|logs|rm)
    docker $* $CONTAINER
    ;;
  cp)
    docker cp $CONTAINER:$2 $3
  ;;
  port)
    docker port $CONTAINER $2
  ;;
  top)
    if [ -z $2 ]
    then
      docker top $CONTAINER
    else
      shift
      docker top $CONTAINER ps $*
    fi
  ;;
  *)
    usage
esac
